import type { Metadata } from "next";
import "./globals.css";
import { Open_Sans } from '@next/font/google';
import { ConfigProvider } from "antd";
import { Fragment, Suspense } from "react";
import { BaseLayout } from "@/Layout/Base";

const openSansFont = Open_Sans({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Bolos caseiros e variedades",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSansFont.className}>
        <main>
          <BaseLayout>
            {children}
          </BaseLayout>
        </main>
      </body>
    </html>
  );
}