import type { Metadata } from "next";
import { Open_Sans } from "@next/font/google";
import { BaseLayout } from "@/Layout/Base";
import "./globals.css";
import { SideBar } from "@/components/SideBar/SideBar";
import { Stack } from "@mui/material";
import { Header } from "@/components/Header/Header";
import { StructureLayout } from "@/Layout/StructureLayout/StructureLayout";
import { Providers } from "@/Contexts/Providers";

const openSansFont = Open_Sans({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bolos caseiros e variedades",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSansFont.className}>
        <Providers>
          <StructureLayout>
            {children}
          </StructureLayout>
        </Providers>
      </body>
    </html>
  );
}
