import type { Metadata } from "next";
import "./globals.css";
import { Open_Sans } from '@next/font/google';
import { ConfigProvider } from "antd";
import { configTheme } from "@/theme/ConfigTheme";
import { Fragment, Suspense } from "react";
import { BaseLayout } from "@/Layout/Base";
import { Header } from "@/components/Header";

const openSansFont = Open_Sans({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Bolos caseiros e variedades",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConfigProvider {...{
        theme: configTheme
      }}>
        <body className={openSansFont.className}>
          <header>
            <Header />
          </header>
          <main>
            <BaseLayout>
              {children}
            </BaseLayout>
          </main>
        </body>
      </ConfigProvider>
    </html>
  );
}